# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set work directory
WORKDIR /app

# Copy project files
COPY . /app

# Install uv CLI and package dependencies
RUN pip install --no-cache-dir uv \
    && pip install --no-cache-dir .

# Default command to run the MCP server using uvx
CMD ["uvx", "amap-mcp"]
